[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
sort_imports = true
quote_style = "double"
wrap_comments = true
int_types = "long"
contract_new_lines = true
multiline_func_header = "attributes_first"

[fuzz]
runs = 256
